[package]
name = "deepgram"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# TODO Investigate which of these dependencies can go behind features.
bytes = "1.1.0"
futures = "0.3.21"
http = "0.2.6"
pin-project = "1.0.10"
reqwest = { version = "0.11.10", features = ["json"] }
serde = { version = "1.0.136", features = [ "derive" ] }
serde_json = "1.0.79"
thiserror = "1.0.30"
tokio = { version = "1.17.0", features = [ "full" ] }
tokio-tungstenite = { version = "0.17.1", features = [ "native-tls" ] }
tokio-util = { version = "0.7.1", features = [ "codec", "io" ] }
tungstenite = "0.17.2"
url = "2.2.2"

[dev-dependencies]
cpal = "0.13.5"
crossbeam = "0.8.1"
reqwest = { version = "0.11.10", features = ["stream"] }
serde_urlencoded = "0.7.1"
form_urlencoded = "1.0.1"
